-- Arts & Crafts activities — ages 0–5, 20 per age group (120 total)
-- Run in Supabase SQL Editor after seed.sql

INSERT INTO activities (age, title, emoji, color, area, subject, duration, materials, steps, prior_stage, prior_desc, safety, ease_of_prep, is_custom) VALUES

-- ── AGE 0 ──────────────────────────────────────────────────────────────────
(0, 'Sensory Paint Bag', '🎨', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['zip-lock bag', 'washable paint (2 colours)', 'strong tape'],
  ARRAY['Squeeze two blobs of paint into the bag.', 'Seal tightly and tape edges shut.', 'Lay flat and let baby push the colours around with fingers.', 'Point to colour changes and name them.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Ensure bag is fully sealed before handing to baby.', 4, false),

(0, 'Edible Finger Paint Tray', '🖐️', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['plain yogurt', 'food colouring (red, yellow, blue)', 'high-chair tray or baking tray'],
  ARRAY['Divide yogurt into three small bowls.', 'Add a drop of food colouring to each.', 'Place spoonfuls on the tray in front of baby.', 'Let baby smear and explore freely.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 3, false),

(0, 'Crinkle Foil Art', '✨', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['sheet of kitchen foil', 'coloured paper underneath'],
  ARRAY['Place coloured paper on a flat surface.', 'Lay the foil sheet on top.', 'Help baby scrunch and crinkle the foil.', 'Remove foil to reveal crinkle pattern imprinted on paper.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Supervise closely — no loose foil pieces near mouth.', 3, false),

(0, 'Cotton Ball Dabbing', '☁️', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['cotton balls', 'washable paint', 'paper', 'paint tray'],
  ARRAY['Pour a small amount of paint onto the tray.', 'Dip a cotton ball in paint.', 'Guide baby''s hand to dab it on paper.', 'Repeat with a second colour.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 3, false),

(0, 'Handprint Keepsake', '🖐️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '5–15 min',
  ARRAY['washable paint', 'card stock', 'damp cloth for clean-up'],
  ARRAY['Brush a thin layer of paint on baby''s palm.', 'Press firmly onto card stock.', 'Lift straight up.', 'Wipe hand clean, let print dry.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Use baby-safe, non-toxic paint only.', 3, false),

(0, 'High-Contrast Fabric Squares', '⬛', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['black and white fabric scraps', 'basket'],
  ARRAY['Cut fabric into palm-sized squares with different textures.', 'Place in a low basket within baby''s reach.', 'Hold each up close for baby to focus on the pattern.', 'Let baby grab and feel each texture.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 3, false),

(0, 'Bubble Wrap Footprint', '🦶', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '5–15 min',
  ARRAY['bubble wrap (large bubbles)', 'washable paint', 'paper'],
  ARRAY['Lay paper on floor.', 'Brush paint on bubble wrap sheet.', 'Hold baby safely and press feet onto bubble wrap.', 'Press feet onto paper to transfer print.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Hold baby securely throughout.', 4, false),

(0, 'Ribbon Waving Visual', '🎀', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['colourful ribbons (30 cm each)', 'ring or cardboard tube'],
  ARRAY['Thread ribbons through a cardboard tube or ring.', 'Tie off so they hang loosely.', 'Wave slowly in front of baby.', 'Let baby bat at ribbons.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Keep ribbon lengths short to avoid entanglement.', 2, false),

(0, 'Watercolour Splash on Wet Paper', '💧', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['watercolour paint', 'thick paper', 'water spray bottle', 'dropper'],
  ARRAY['Spray paper with water until damp.', 'Drop small amounts of diluted watercolour onto paper.', 'Let baby watch colours spread and blend.', 'Tilt paper gently to guide colour flow.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 3, false),

(0, 'Soft Sponge Imprint', '🟣', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['bath sponge', 'washable paint', 'paper', 'paint tray'],
  ARRAY['Wet the sponge slightly, squeeze out excess.', 'Dip in paint.', 'Guide baby''s hand to press sponge on paper.', 'Lift to see shape.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 3, false),

(0, 'Colour Mixing Zip Bag', '🔵', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['zip-lock bag', 'yellow paint', 'blue paint', 'tape'],
  ARRAY['Add a blob of yellow and a blob of blue paint to the bag.', 'Seal and tape edges.', 'Lay flat; guide baby to press and mix colours.', 'Watch green appear and name it.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Tape bag thoroughly before play.', 3, false),

(0, 'Tissue Paper Scrunch', '🌸', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['sheets of tissue paper in 3 colours'],
  ARRAY['Tear tissue paper into large pieces.', 'Lay a sheet in baby''s hands.', 'Help baby crunch and scrunch.', 'Stack scrunched pieces to make a colourful pile.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Supervise; do not leave baby with loose paper.', 2, false),

(0, 'Cloud Dough Sensory', '🌫️', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['2 cups plain flour', '1/4 cup baby oil', 'food colouring (optional)', 'tray'],
  ARRAY['Mix flour and baby oil until it clumps like wet sand.', 'Add a drop of food colouring if desired.', 'Place on tray and let baby squeeze and pat.', 'Show how it holds shape when squeezed.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Not suitable for mouthing — supervise closely.', 4, false),

(0, 'Nature Leaf Touch Print', '🍃', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '5–15 min',
  ARRAY['large flat leaf', 'washable paint', 'paper'],
  ARRAY['Brush paint on the back of the leaf (veins side).', 'Press leaf paint-side down on paper.', 'Guide baby''s hand to press gently.', 'Peel back to reveal print.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 3, false),

(0, 'Foil Crinkle Sculpture', '🔮', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['sheet of kitchen foil'],
  ARRAY['Tear off a 30 cm sheet of foil.', 'Help baby scrunch it loosely into a ball.', 'Smooth and re-scrunch a few times.', 'Let baby hold and feel the finished sculpture.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Keep foil pieces large enough not to be swallowed.', 2, false),

(0, 'Paint Bag Mark-Making', '✏️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '5–15 min',
  ARRAY['zip-lock bag', 'hair gel', 'glitter', 'tape'],
  ARRAY['Fill bag with hair gel and a pinch of glitter.', 'Seal and tape shut.', 'Lay flat; help baby drag a finger across it.', 'Shake to erase and start again.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Tape completely; no gel should escape.', 3, false),

(0, 'Mirror Face Exploration', '🪞', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '5–15 min',
  ARRAY['unbreakable baby mirror', 'face paints or washable dot stickers'],
  ARRAY['Hold mirror so baby can see their face clearly.', 'Place a coloured dot sticker on your cheek.', 'Let baby notice and reach toward the reflection.', 'Make expressive faces together.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 2, false),

(0, 'Sponge Bath Painting', '🛁', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['bath-safe finger paint', 'bath sponges in different shapes'],
  ARRAY['Add a small amount of bath-safe paint to bath water or tray.', 'Hand a sponge to baby.', 'Let baby swirl and splash the coloured water.', 'Demonstrate dabbing sponge on the bath side.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Use only bath-safe, non-toxic paint. Never leave baby unattended near water.', 3, false),

(0, 'Peek-a-Boo Fabric Art', '👀', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '5–15 min',
  ARRAY['brightly coloured fabric scraps', 'basket'],
  ARRAY['Arrange colourful fabric pieces in a basket.', 'Cover one piece with another.', 'Say peekaboo! and pull the cover away.', 'Let baby pull fabrics out and scrunch them.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 2, false),

(0, 'Chalk Dust Finger Trail', '🖊️', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '5–15 min',
  ARRAY['chunky blackboard chalk', 'dark paper or slate board'],
  ARRAY['Rub chalk across dark paper to create coloured dust.', 'Guide baby''s finger through the dust.', 'Notice the trails and marks left behind.', 'Blow gently to move the dust.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Keep chalk pieces large. Wipe baby''s hands after play.', 3, false),

-- ── AGE 1 ──────────────────────────────────────────────────────────────────
(1, 'Finger Painting Free Play', '🎨', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['washable finger paint (3 colours)', 'large paper taped to table'],
  ARRAY['Tape paper to the table surface.', 'Spoon a small amount of each colour onto the paper.', 'Encourage child to spread, mix and explore freely.', 'Name colours as they appear.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Use non-toxic washable paint.', 3, false),

(1, 'Chunky Crayon Scribble', '🖍️', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '10–20 min',
  ARRAY['chunky crayons', 'large paper'],
  ARRAY['Place large paper on the floor.', 'Hand child a chunky crayon.', 'Make big swooping marks together to start.', 'Step back and let child scribble freely.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 2, false),

(1, 'Sponge Stamp Printing', '🟪', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['kitchen sponges cut into shapes', 'washable paint', 'paper', 'paint tray'],
  ARRAY['Cut sponges into simple shapes (circle, square, star).', 'Pour paint into flat tray.', 'Dip sponge in paint and press onto paper.', 'Try each shape and colour.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 4, false),

(1, 'Chalk on Pavement', '🖊️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['chunky outdoor chalk', 'paved outdoor area'],
  ARRAY['Hand child a piece of chunky chalk.', 'Draw a large circle on the pavement as a starting point.', 'Let child add to it freely.', 'Trace child''s hands or feet if interested.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 2, false),

(1, 'Sticker Collage', '⭐', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '10–20 min',
  ARRAY['large dot stickers in many colours', 'paper'],
  ARRAY['Place paper on a low table.', 'Show child how to peel a sticker from the sheet.', 'Let child place stickers anywhere on the paper.', 'Count stickers together as you go.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 2, false),

(1, 'Torn Paper Collage', '📰', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '10–20 min',
  ARRAY['colourful magazine pages', 'glue stick', 'paper'],
  ARRAY['Tear magazine pages into rough pieces together.', 'Spread glue stick on paper.', 'Let child press torn pieces onto glued surface.', 'Overlap pieces for a layered effect.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 3, false),

(1, 'Playdough Squish and Poke', '🟣', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '10–20 min',
  ARRAY['playdough', 'blunt poke tools (wooden spoon, fork, coin)'],
  ARRAY['Give child a ball of playdough.', 'Demonstrate squishing it flat with a palm.', 'Press a fork or coin into the surface.', 'Pull apart and squish back together.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 2, false),

(1, 'Water Painting on Dark Card', '💧', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['dark card or slate', 'thick paintbrush', 'cup of water'],
  ARRAY['Fill cup with water.', 'Hand child the brush and show how to dip in water.', 'Brush water onto dark card to see marks appear.', 'Watch marks fade and paint again.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 2, false),

(1, 'Bubble Print Art', '🫧', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['bubble mixture', 'food colouring', 'cups', 'straws', 'paper'],
  ARRAY['Add food colouring to bubble mixture in cups.', 'Blow through straw until bubbles overflow cup.', 'Press paper gently over the bubbles.', 'Lift to reveal circular prints.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Ensure child blows OUT through straw — demonstrate first.', 4, false),

(1, 'Cotton Ball Stamping', '☁️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['cotton balls', 'clothes pegs', 'washable paint', 'paper'],
  ARRAY['Clip a clothes peg to a cotton ball to make a stamp tool.', 'Dip cotton ball in paint.', 'Press onto paper to make fluffy marks.', 'Use several colours.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 3, false),

(1, 'Nature Collage Pressing', '🍂', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['collected leaves, petals, grass', 'paper', 'glue stick'],
  ARRAY['Collect natural items on a short walk.', 'Spread glue on paper.', 'Press leaves, petals and grass onto the glue.', 'Let dry and admire the natural artwork.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Check for thorns before handling. Wash hands after.', 3, false),

(1, 'Footprint Animal Art', '🐾', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['washable paint', 'tray', 'paper', 'markers for adding details'],
  ARRAY['Pour paint in tray.', 'Help child step into tray then onto paper.', 'Clean foot immediately.', 'Add eyes and details with markers to make an animal.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Hold child steady. Clean feet promptly.', 4, false),

(1, 'Shaving Cream Drawing', '🌊', '#c084fc', 'Arts & Crafts · Sensory', 'Arts & Crafts', '10–20 min',
  ARRAY['shaving cream (fragrance-free)', 'high-chair tray or baking tray', 'food colouring (optional)'],
  ARRAY['Squirt a layer of shaving cream onto the tray.', 'Add a drop of food colouring if desired.', 'Let child spread and draw in it with fingers.', 'Swipe flat to erase and start again.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Keep away from eyes. Use fragrance-free foam.', 3, false),

(1, 'Big Brush Painting', '🖌️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['large decorating brush', 'washable paint', 'large paper on floor'],
  ARRAY['Tape large paper to the floor.', 'Mix paint to a runny consistency.', 'Hand child the big brush.', 'Encourage wide sweeping strokes.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 3, false),

(1, 'Foam Shape Printing', '🔷', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['foam shapes (from craft shop or cut bath foam)', 'washable paint', 'paper'],
  ARRAY['Lay foam shapes on paint tray.', 'Press a shape firmly into paint.', 'Press shape onto paper.', 'Try each shape and layer colours.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 3, false),

(1, 'Glitter Glue Picture', '✨', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['glitter glue pens', 'thick paper'],
  ARRAY['Open glitter glue pens.', 'Show child how to squeeze gently.', 'Encourage dots and lines on paper.', 'Let dry completely before touching.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Supervise use of pens.', 3, false),

(1, 'Pasta Necklace Threading', '📿', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '10–20 min',
  ARRAY['large tube pasta (penne)', 'thick shoelace or pipe cleaner', 'food colouring (to dye pasta if desired)'],
  ARRAY['Stiffen end of shoelace with tape.', 'Show child how to push pasta onto the lace.', 'Thread several pieces together.', 'Tie ends to make a necklace.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Use pasta too large to swallow. Supervise.', 3, false),

(1, 'Colour Sorting Dot Game', '🔴', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '10–20 min',
  ARRAY['dot stickers in 3 colours', 'paper with matching coloured circles drawn on it'],
  ARRAY['Draw large circles in red, blue and yellow on paper.', 'Give child matching coloured dot stickers.', 'Encourage placing dots inside the matching circle.', 'Praise each correct match.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 3, false),

(1, 'Handprint Rainbow', '🌈', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '10–20 min',
  ARRAY['washable paint in rainbow colours', 'large paper', 'damp cloth'],
  ARRAY['Paint child''s hand in red.', 'Press and lift to make first arc.', 'Clean hand, apply orange next.', 'Continue through rainbow colours to make arcs.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Clean between colours promptly.', 4, false),

(1, 'Tray Dough Shapes', '🟡', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '10–20 min',
  ARRAY['playdough', 'simple shape cutters', 'rolling pin'],
  ARRAY['Give child a lump of dough on a flat tray.', 'Roll flat with rolling pin together.', 'Press a cutter down firmly.', 'Lift cutter to reveal shape.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 2, false),

-- ── AGE 2 ──────────────────────────────────────────────────────────────────
(2, 'Marble Run Painting', '🔮', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['marbles', 'washable paint', 'paper in a box lid', 'spoon'],
  ARRAY['Place paper inside a box lid.', 'Drop a spoonful of paint onto paper.', 'Add a marble, tip the box side to side.', 'Add a second colour and continue.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Marbles are choking hazard — do not leave unattended.', 4, false),

(2, 'Potato Print Art', '🥔', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['potato halves', 'knife (adult use)', 'washable paint', 'paper'],
  ARRAY['Adult cuts potato half into a simple shape.', 'Press cut face into paint tray.', 'Stamp firmly onto paper.', 'Repeat across paper to make a pattern.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Adult handles knife. Let child only touch carved potato.', 4, false),

(2, 'Butterfly Symmetry Print', '🦋', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['paint', 'paper'],
  ARRAY['Fold paper in half and open out again.', 'Drop paint blobs on one half.', 'Fold paper together and press firmly.', 'Open to reveal symmetrical butterfly pattern.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Crayon Rubbing', '✏️', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['chunky crayons with paper removed', 'textured objects (coins, leaves, corrugated card)', 'thin paper'],
  ARRAY['Place a textured object under thin paper.', 'Rub the side of the crayon across the paper.', 'Watch the texture appear.', 'Try three different textures.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Glue Collage Mix', '🎭', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['PVA glue', 'brush', 'paper', 'feathers, buttons, fabric scraps, dried pasta'],
  ARRAY['Lay materials out in small piles.', 'Brush glue onto paper.', 'Let child choose materials and press on.', 'Allow to dry flat.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Buttons and small items — supervise. Not for mouthers.', 3, false),

(2, 'Salt Dough Making', '🧂', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['1 cup flour', '1/2 cup salt', '1/2 cup water', 'baking tray', 'shape cutters'],
  ARRAY['Mix flour, salt and water into a dough.', 'Knead together for 2 minutes.', 'Roll out and cut shapes.', 'Bake at 120°C for 2 hours until hard.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Adult handles oven. Dough is salty — discourage eating.', 4, false),

(2, 'Toilet Roll Characters', '🐛', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['toilet roll tubes', 'paint', 'googly eyes (optional)', 'glue', 'felt tip markers'],
  ARRAY['Paint the outside of a tube.', 'Let dry.', 'Glue on googly eyes.', 'Add details with marker.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Leaf Rubbing Collection', '🍁', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['leaves in different sizes', 'crayons', 'thin white paper'],
  ARRAY['Collect a variety of leaves.', 'Place leaf vein-side up under paper.', 'Rub crayon across paper over leaf.', 'Fill page with different leaf prints.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 2, false),

(2, 'Colour Mixing Painting', '🔵', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['red, yellow and blue paint', 'paintbrush', 'paper', 'palette or ice cube tray'],
  ARRAY['Put red, yellow and blue paint in palette sections.', 'Ask child what colour they predict mixing two will make.', 'Mix and paint a patch.', 'Work through all three combinations.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Pasta Picture', '🍝', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['dried pasta in varied shapes', 'PVA glue', 'paper', 'paint (optional)'],
  ARRAY['Spread glue on paper in an area.', 'Press pasta pieces to form a picture.', 'Let dry fully.', 'Paint over if desired.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Supervise — small pasta can be a choking hazard.', 3, false),

(2, 'Tissue Paper Flower', '🌸', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['tissue paper in 3 colours', 'pipe cleaners', 'scissors (adult use)'],
  ARRAY['Stack 5 squares of tissue paper.', 'Fold accordion style.', 'Pinch in the middle and twist a pipe cleaner around.', 'Fan each layer out to form petals.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Handprint Art', '🖐️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['paint', 'paper', 'markers'],
  ARRAY['Trace child''s hand onto paper.', 'Let child paint inside the outline.', 'When dry add details with marker.', 'Display or send as a gift.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Button Colour Sort Art', '🔴', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['large buttons (at least 2 holes) in primary colours', 'PVA glue', 'card', 'pencil'],
  ARRAY['Draw coloured circles on card with pencil.', 'Give child glue and buttons.', 'Encourage sorting buttons onto matching circles.', 'Press each button firmly into glue.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Buttons must be large — no small buttons near children under 3.', 3, false),

(2, 'Sponge Watercolour Wash', '🌊', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['watercolour paint set', 'fat paintbrush', 'thick paper', 'water'],
  ARRAY['Wet paper lightly with a damp sponge.', 'Load brush with watercolour.', 'Stroke across wet paper.', 'Watch colours bleed and blend.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Newspaper Papier-Mâché Ball', '⚽', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['newspaper', 'PVA glue diluted with water', 'balloon', 'paintbrush'],
  ARRAY['Inflate balloon to small size.', 'Tear newspaper into strips.', 'Paint strips with glue and layer on balloon.', 'Let dry before adding next layer (repeat 2–3 times).'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Pop balloon only after layers are fully dry. Adult task.', 5, false),

(2, 'Ribbon Weave Card', '🎀', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['stiff card with holes pre-punched in a grid', 'colourful ribbon or shoelace', 'scissors (adult use)'],
  ARRAY['Punch grid of holes in card.', 'Thread ribbon up through first hole.', 'Guide child to continue weaving in and out.', 'Tie off at the end.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 4, false),

(2, 'Scratch Art Drawing', '✏️', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['white card', 'wax crayons in bright colours', 'black paint or black crayon', 'pointy wooden skewer (adult supervision)'],
  ARRAY['Cover card heavily with bright crayon colours.', 'Paint over with black paint.', 'Let dry completely.', 'Scratch a picture through the black to reveal colours.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Use rounded skewer. Adult supervises scratching tool.', 5, false),

(2, 'Torn Paper Mosaic', '🖼️', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '15–30 min',
  ARRAY['coloured paper', 'glue stick', 'paper base', 'pencil drawing outline'],
  ARRAY['Draw a simple shape outline on base paper.', 'Tear coloured paper into small pieces.', 'Glue pieces inside the outline to fill it.', 'Add a contrasting border.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Soda Bottle Print', '🔵', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['plastic bottle ends (cut by adult)', 'washable paint', 'paper'],
  ARRAY['Cut bottom off a plastic bottle (adult task).', 'Dip cut end in paint.', 'Press onto paper to make a flower-like print.', 'Repeat with different colours.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Adult cuts bottle and checks for sharp edges before handing to child.', 4, false),

(2, 'Easel Free Painting', '🖌️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['easel or paper taped to wall', 'thick paintbrushes', 'washable paint in 4 colours'],
  ARRAY['Fix paper to easel at child''s height.', 'Set out paints in pots.', 'Give child brushes and let them paint freely.', 'Encourage large strokes and filling the page.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Paper Bag Puppet', '🎭', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '15–30 min',
  ARRAY['paper lunch bag', 'markers', 'googly eyes', 'glue', 'felt scraps'],
  ARRAY['Fold flap of bag as puppet mouth.', 'Glue googly eyes above flap.', 'Draw or glue felt details for face.', 'Slide hand in to animate puppet.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

-- ── AGE 3 ──────────────────────────────────────────────────────────────────
(3, 'Wax Resist Watercolour', '🎨', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['white wax candle or white crayon', 'watercolour paint', 'thick paper', 'paintbrush'],
  ARRAY['Draw a picture with the white wax candle on paper.', 'Paint over the whole page with watercolour.', 'Watch the hidden drawing appear.', 'Try a night sky: white stars appear through blue wash.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 3, false),

(3, 'Junk Model Building', '🤖', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['cardboard boxes and tubes', 'masking tape', 'PVA glue', 'paint', 'markers'],
  ARRAY['Collect a range of cardboard packaging.', 'Decide what to build (robot, car, animal).', 'Join pieces with tape and glue.', 'Paint and decorate when structure is dry.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'String Art', '🧵', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '20–35 min',
  ARRAY['string or wool', 'PVA glue diluted', 'dark paper', 'bowl for dipping'],
  ARRAY['Pour diluted PVA glue into bowl.', 'Dip string in glue.', 'Arrange string on paper in a pattern or shape.', 'Let dry flat for 2 hours.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Clay Pinch Pot', '🏺', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '20–35 min',
  ARRAY['air-dry clay', 'water', 'smooth stone or wooden tool'],
  ARRAY['Roll clay into a ball.', 'Push thumbs into the centre.', 'Pinch walls up evenly all around.', 'Smooth with wet finger. Let air-dry for 24 hours.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 3, false),

(3, 'Salt Painting', '🧂', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['PVA glue in squeeze bottle', 'table salt', 'watercolour paint', 'card', 'droppers'],
  ARRAY['Draw a design with PVA glue on card.', 'Quickly pour salt over all the glue.', 'Shake off excess.', 'Drop watercolour onto salt and watch it spread.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Simple Weaving Frame', '🧶', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '20–35 min',
  ARRAY['stiff card with slits cut top and bottom', 'wool in 2 colours', 'blunt needle'],
  ARRAY['Weave wool vertically through card slits to create warp.', 'Thread blunt needle with contrasting wool.', 'Weave over-under through vertical strands.', 'Push rows down to tighten.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Paper Mosaic Animal', '🦊', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '20–35 min',
  ARRAY['coloured paper', 'scissors (child-safe)', 'glue stick', 'printed animal outline'],
  ARRAY['Print or draw a large animal outline.', 'Cut coloured paper into small squares.', 'Glue squares in rows inside the outline.', 'Leave small gaps to create mosaic effect.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Accordion Fold Story Book', '📖', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['long strip of paper', 'markers and crayons'],
  ARRAY['Fold paper strip accordion style to create pages.', 'Decide on a simple 4-part story.', 'Draw one scene per page.', 'Read the story together.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 2, false),

(3, 'Nature Mandala', '🌿', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['natural materials: leaves, petals, pebbles, twigs', 'flat outdoor surface or tray'],
  ARRAY['Arrange a stone or pinecone at the centre.', 'Place leaves radiating outward in a ring.', 'Add petals between leaves.', 'Continue adding rings outward.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Wash hands after handling soil or berries.', 2, false),

(3, 'Decoupage Bowl', '🥣', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '20–35 min',
  ARRAY['balloon', 'diluted PVA glue', 'tissue paper strips', 'paintbrush'],
  ARRAY['Inflate balloon to bowl size.', 'Brush glue on outside of bottom half.', 'Layer tissue strips overlapping.', 'Add 3 layers and let dry before popping balloon.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Adult pops balloon. Latex allergy check.', 5, false),

(3, 'Cardboard Tube Castle', '🏰', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['cardboard tubes (various sizes)', 'cardboard base', 'masking tape', 'paint'],
  ARRAY['Arrange tubes on cardboard base as towers.', 'Tape tubes securely to base and to each other.', 'Add battlements cut from card.', 'Paint castle grey or brown.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Monoprint Making', '🖼️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['acrylic or washable paint', 'smooth plastic board or plastic sheet', 'paper', 'roller or sponge'],
  ARRAY['Roll a thin layer of paint on the plastic sheet.', 'Draw into the paint with a finger or stick.', 'Place paper on top and press gently.', 'Peel back to reveal mirror print.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Mixed Media Collage', '🌈', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['base paper', 'watercolour wash', 'magazine cutouts', 'glue', 'markers', 'fabric scraps'],
  ARRAY['Paint paper with watercolour wash.', 'Cut or tear magazine images.', 'Glue images over dry paint.', 'Add markers, fabric or other materials on top.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Adult cuts with scissors if sharp.', 4, false),

(3, 'Colour Wheel Painting', '🟡', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['red, yellow, blue paint', 'paper', 'pencil', 'compass or round objects for circles'],
  ARRAY['Draw a large circle and divide into 6 sections.', 'Paint red, yellow and blue in alternate sections.', 'Mix red+yellow in the section between them (orange).', 'Fill remaining sections with green and purple.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Transfer Print', '🔄', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['acetate sheet or smooth plastic', 'acrylic paint', 'paper'],
  ARRAY['Paint a picture on the acetate.', 'While still wet, press paper on top.', 'Rub firmly across paper back.', 'Peel up to reveal transferred print.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Scratch Art Reveal', '🎇', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '20–35 min',
  ARRAY['bright crayons', 'black acrylic paint', 'paper', 'wooden skewer'],
  ARRAY['Colour card heavily in bright patches.', 'Paint completely over with black paint.', 'Let dry for one hour.', 'Scratch designs to reveal the colours.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Use blunt skewer. Adult supervision during scratching.', 5, false),

(3, 'Printing Press Pattern', '🖨️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['foam sheet cut into shapes', 'washable ink or paint', 'tray', 'large paper'],
  ARRAY['Cut foam shapes (adult).', 'Roll thin ink layer on foam shapes.', 'Press shape onto paper.', 'Repeat in a deliberate pattern across the paper.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Paper Chain Bunting', '🎉', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '20–35 min',
  ARRAY['strips of coloured paper (2 × 20 cm)', 'glue stick', 'string'],
  ARRAY['Loop a strip into a circle and glue ends.', 'Thread next strip through first loop and glue.', 'Continue adding loops alternating colours.', 'Hang finished chain as bunting.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 2, false),

(3, 'Printed Fabric Gift Wrap', '🎁', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['plain paper or tissue paper', 'sponge shapes', 'fabric paint or washable paint'],
  ARRAY['Lay paper flat on protected surface.', 'Dip sponge shape into paint.', 'Print across paper in a repeating pattern.', 'Let dry and use as gift wrap.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 3, false),

(3, 'Sock Puppet Theatre', '🎭', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '20–35 min',
  ARRAY['old socks', 'googly eyes', 'glue', 'felt offcuts', 'markers'],
  ARRAY['Slip sock onto hand.', 'Glue googly eyes above thumb fold.', 'Cut and glue felt shapes for hair, nose, mouth.', 'Put on a short puppet show.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 3, false),

-- ── AGE 4 ──────────────────────────────────────────────────────────────────
(4, 'Watercolour Portrait', '🖼️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['watercolour paints', 'thick paper', 'pencil', 'paintbrush', 'water'],
  ARRAY['Lightly sketch a face with pencil.', 'Mix skin tone from red, yellow and white.', 'Paint skin area and let dry.', 'Add hair, eyes and background in layers.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 4, false),

(4, 'Simple Origami Shapes', '🦢', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '25–40 min',
  ARRAY['square origami paper (or plain paper cut square)', 'instructions for dog or boat'],
  ARRAY['Start with square paper, coloured side down.', 'Fold in half diagonally and crease firmly.', 'Follow next fold step.', 'Complete chosen shape together.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 3, false),

(4, 'Loom Weaving', '🧶', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '25–40 min',
  ARRAY['small cardboard loom with notches cut', 'wool in 3 colours', 'blunt tapestry needle'],
  ARRAY['Warp loom by winding wool through notches top to bottom.', 'Thread needle with contrasting colour.', 'Weave over-under across the warp.', 'Change colour after several rows.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 5, false),

(4, 'Stencil Painting', '🔡', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['card to make stencil', 'child-safe scissors', 'sponge', 'paint', 'paper'],
  ARRAY['Cut a simple shape from the centre of card.', 'Place stencil on paper.', 'Dab sponge with paint inside the cut-out shape.', 'Lift stencil to reveal clean edges.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 4, false),

(4, 'Marbling Paper', '🌀', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['shaving foam', 'food colouring in 3 colours', 'tray', 'paper', 'card scraper'],
  ARRAY['Spread shaving foam in tray.', 'Drop food colouring in lines across foam.', 'Drag a skewer through to create swirls.', 'Press paper down, lift, scrape foam off to reveal marble pattern.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 5, false),

(4, 'Clay Pot with Texture', '🏺', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '25–40 min',
  ARRAY['air-dry clay', 'textured objects (fork, coin, fabric)', 'water'],
  ARRAY['Build a pinch pot from clay.', 'Press textured objects into the outside of the pot.', 'Smooth interior with a damp finger.', 'Let dry 24–48 hours.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 3, false),

(4, 'Papier-Mâché Mask', '🎭', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['balloon', 'newspaper strips', 'diluted PVA glue', 'paint', 'elastic'],
  ARRAY['Coat balloon with petroleum jelly.', 'Layer newspaper strips dipped in glue.', 'Build up 4 layers, drying between sets.', 'Pop balloon, trim edges, cut eye holes, paint and attach elastic.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Adult pops balloon. Check elastic length for comfort.', 6, false),

(4, 'Wire Pipe Cleaner Sculpture', '🦋', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '25–40 min',
  ARRAY['pipe cleaners in many colours', 'beads (optional)'],
  ARRAY['Plan a creature or shape to make.', 'Twist two pipe cleaners together as a body.', 'Bend and add legs, wings or antennae.', 'Thread beads if desired.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Tuck in sharp wire ends. Beads — supervise.', 3, false),

(4, 'Shadow Drawing Outside', '☀️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['objects to cast shadows (plant, toy, cup)', 'paper', 'pencil or chalk'],
  ARRAY['Place an object on paper in full sunlight.', 'Trace the shadow outline quickly.', 'Move object, trace again.', 'Layer multiple shadow drawings on one sheet.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 2, false),

(4, 'Pressed Flower Bookmark', '🌼', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '25–40 min',
  ARRAY['fresh flowers and leaves', 'heavy books', 'card strips', 'clear contact paper'],
  ARRAY['Press flowers between paper in a heavy book for 1 week.', 'Cut card into bookmark strips.', 'Arrange dried flowers on card.', 'Cover with clear contact paper to seal.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Wash hands after handling plants.', 4, false),

(4, 'Mosaic Coaster', '🔷', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '25–40 min',
  ARRAY['cork tile or thick card square', 'small paper squares or coloured tissue', 'PVA glue', 'brush'],
  ARRAY['Cut paper into small equal squares.', 'Brush glue on tile section by section.', 'Press coloured squares in a pattern.', 'Let dry; brush top coat of PVA to seal.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 4, false),

(4, 'Tie-Dye Paper', '🌈', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['coffee filter papers or tissue paper', 'washable ink or food dye', 'cups of water', 'rubber bands'],
  ARRAY['Fold filter paper into quarters.', 'Bind with a rubber band.', 'Dip each corner in a different colour dye.', 'Open carefully and lay flat to dry.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Dye stains — protect surfaces and clothing.', 4, false),

(4, 'Block Printing Pattern', '🟦', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['foam sheet', 'pencil', 'scissors', 'washable ink', 'roller', 'paper'],
  ARRAY['Draw a simple design on foam sheet.', 'Press firmly with pencil to emboss lines.', 'Roll ink over foam surface.', 'Press foam ink-side down onto paper; lift cleanly.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 5, false),

(4, 'Mixed Media Self-Portrait', '🧒', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['photo of child''s face', 'magazine scraps', 'fabric', 'paint', 'glue', 'paper'],
  ARRAY['Glue photo or draw face outline on paper.', 'Paint in background.', 'Cut and glue fabric or magazine for hair, clothes.', 'Add details with marker.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 4, false),

(4, 'String Pull Design', '🌀', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['wool or thick string', 'washable paint', 'paper folded in half'],
  ARRAY['Dip string in paint, leaving one end clean.', 'Lay string inside folded paper in a loop.', 'Press paper firmly and slowly pull string out.', 'Open to reveal symmetrical pattern.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 3, false),

(4, 'Batik-Inspired Wax Art', '🌀', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['white crayon or wax resist', 'paper', 'watered-down watercolour', 'large brush'],
  ARRAY['Draw a pattern with white crayon all over paper.', 'Mix watercolour to quite dilute consistency.', 'Brush wash over entire page.', 'White wax lines emerge through the colour.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 3, false),

(4, 'Story Mural Roll', '📜', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['wallpaper roll or large paper roll', 'markers and paint', 'tape'],
  ARRAY['Unroll a length of paper on the floor.', 'Plan a story scene together: setting, characters, events.', 'Draw each scene along the roll.', 'Roll up to store; unroll to tell the story.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 3, false),

(4, 'Collograph Print Plate', '🖨️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '25–40 min',
  ARRAY['card base', 'textured materials (string, bubble wrap, corrugated card)', 'PVA glue', 'paint or ink', 'paper'],
  ARRAY['Arrange and glue textures to card base to create print plate.', 'Let dry completely.', 'Roll paint evenly over plate.', 'Press paper firmly, peel back for print.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 5, false),

(4, 'Sgraffito Drawing', '✏️', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '25–40 min',
  ARRAY['thick card', 'paint in 3 colours', 'black paint', 'blunt wooden skewer'],
  ARRAY['Layer brightly coloured paint patches across card.', 'Let dry.', 'Paint over completely with black paint.', 'Scratch away the black to reveal colour beneath.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Use blunt wooden skewer. Adult supervision during scratching phase.', 5, false),

-- ── AGE 5 ──────────────────────────────────────────────────────────────────
(5, 'Watercolour Landscape', '🌅', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['watercolour paints', 'thick paper', 'large and small brushes', 'water', 'masking tape'],
  ARRAY['Tape paper edges for a clean border.', 'Wet top half of paper; paint sky wet-on-wet.', 'Let sky partially dry; paint a tree line or hills.', 'Add foreground details with smaller brush.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 4, false),

(5, 'Simple Perspective Drawing', '🏙️', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '30–50 min',
  ARRAY['pencil', 'ruler', 'paper', 'coloured pencils'],
  ARRAY['Mark a dot in the middle of the paper (vanishing point).', 'Draw two lines from bottom corners to the dot.', 'Add vertical lines between to form buildings.', 'Decorate windows and add a street scene.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 3, false),

(5, 'Zentangle Patterns', '🔮', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '30–50 min',
  ARRAY['white card tiles (9×9 cm)', 'fine black marker', 'pencil'],
  ARRAY['Lightly pencil a border around the tile.', 'Divide into sections with curved pencil lines.', 'Fill each section with a different repeating pattern.', 'Shade borders with pencil to add depth.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 2, false),

(5, 'Pointillism Dot Painting', '🟡', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['paint', 'cotton buds or pencil eraser', 'paper', 'reference image of a simple scene'],
  ARRAY['Choose a simple image (tree, sun, landscape).', 'Sketch lightly in pencil.', 'Dip cotton bud in paint and dab dots inside each section.', 'Cover entire image with dots, changing colours by area.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 3, false),

(5, 'Foam Lino Cut Print', '🖨️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['foam craft sheet', 'pencil for carving', 'washable ink', 'brayer roller', 'paper'],
  ARRAY['Draw a design on foam with pencil, pressing firmly to emboss.', 'Roll ink evenly across foam surface.', 'Press paper firmly over inked foam.', 'Peel paper back; clean foam and re-ink to repeat.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 5, false),

(5, 'Colour Theory Experiment', '🎨', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['red, yellow, blue, white, black paint', 'palette', 'paper', 'brush'],
  ARRAY['Mix red + yellow, yellow + blue, blue + red.', 'Add white to a primary colour: what happens?', 'Add a small amount of black: observe.', 'Paint a colour grid showing all mixes.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 4, false),

(5, 'Architectural Cardboard City', '🏙️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['cardboard boxes, tubes, lids', 'masking tape', 'grey and brown paint', 'markers', 'base board'],
  ARRAY['Plan a city layout on the base board.', 'Construct buildings from boxes, securing with tape.', 'Paint buildings in city colours.', 'Add road markings, signs and details.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 5, false),

(5, 'Still Life Observational Drawing', '🍎', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '30–50 min',
  ARRAY['3–4 household objects (fruit, cup, book)', 'pencil', 'paper', 'coloured pencils or pastels'],
  ARRAY['Arrange objects on a table in good light.', 'Observe the shapes carefully before drawing.', 'Sketch outline lightly then add details.', 'Shade to show light and shadow.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 2, false),

(5, 'Comic Strip Storytelling', '💬', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['paper folded into 6 panels', 'pencil', 'markers', 'ruler'],
  ARRAY['Plan a 6-panel story with a beginning, middle and end.', 'Sketch characters and setting in pencil first.', 'Ink over pencil with marker.', 'Add speech bubbles and colour.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 2, false),

(5, 'Clay Glazed Pot', '🏺', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '30–50 min',
  ARRAY['air-dry clay', 'carving tool', 'acrylic paint (as glaze substitute)', 'brush', 'PVA sealer'],
  ARRAY['Build a pinch pot with even walls.', 'Carve a pattern into outside while clay is leather-hard.', 'Let dry fully (24–48 hours).', 'Paint with diluted acrylic, then seal with PVA coat.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 5, false),

(5, 'Complex Loom Weaving', '🧶', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '30–50 min',
  ARRAY['cardboard loom', 'multiple wool colours', 'blunt needle', 'scissors'],
  ARRAY['Set up warp threads on loom.', 'Weave a base of one colour for 5 rows.', 'Change colour, weave a pattern section.', 'Finish with border row and tie off ends.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 5, false),

(5, 'Monotype Glass Print', '🪟', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['glass or acrylic sheet', 'water-based inks or acrylic paint', 'brayer', 'paper'],
  ARRAY['Roll a thin even layer of ink on glass.', 'Draw directly into the ink with a stick or finger.', 'Lay paper on top and press gently.', 'Peel back carefully — only one print per inking.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Handle glass sheet with care. Adult supervises.', 5, false),

(5, 'Shadow Puppet Theatre', '🎭', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['black card', 'scissors', 'skewers', 'tape', 'white sheet or tracing paper', 'torch or lamp'],
  ARRAY['Draw character outlines on black card and cut out.', 'Tape a skewer to the back of each puppet.', 'Hang white sheet across a doorway.', 'Shine torch behind screen; perform puppet story.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Keep sharp scissor use adult-supervised.', 5, false),

(5, 'Papier-Mâché Painted Bowl', '🥣', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['balloon', 'newspaper strips', 'diluted PVA glue', 'acrylic paint', 'PVA sealer'],
  ARRAY['Build up 6 layers of papier-mâché on half a balloon.', 'Let dry fully (1–2 days).', 'Pop balloon; sand any rough edges.', 'Paint a geometric or nature design; seal with PVA.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Adult pops balloon and sands edges.', 6, false),

(5, 'Artist Study and Recreation', '🖼️', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['printed image of a famous artwork (Mondrian, Kandinsky, Van Gogh)', 'matching materials (paint, ruler, etc.)'],
  ARRAY['Look at the artwork together and discuss colours, shapes, style.', 'Identify the key elements to recreate.', 'Sketch layout lightly in pencil.', 'Recreate using the same technique.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 4, false),

(5, 'Collaborative Mural', '🎨', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['large paper roll taped to wall', 'paints in many colours', 'brushes', 'rollers'],
  ARRAY['Plan a theme together (underwater, jungle, city).', 'Each person takes a section to paint.', 'Fill the whole paper with a connected scene.', 'Share work and explain your part.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 4, false),

(5, 'Wire and Bead Sculpture', '🌟', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '30–50 min',
  ARRAY['craft wire', 'beads in varied sizes', 'wire cutters (adult use)', 'pliers'],
  ARRAY['Adult cuts wire lengths with wire cutters.', 'Child threads beads onto wire.', 'Bend wire into a 3D shape (person, star, animal).', 'Tuck sharp wire ends with pliers (adult).'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Adult handles wire cutting and tucking sharp ends.', 5, false),

(5, 'Batik Fabric Square', '🌀', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['white cotton fabric square', 'wax crayons', 'liquid fabric dye or diluted acrylic', 'brush', 'iron (adult)'],
  ARRAY['Draw a bold design on fabric with wax crayon, pressing firmly.', 'Paint diluted dye over the whole fabric.', 'Let dry.', 'Adult irons between paper to melt wax and fix dye.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Adult uses iron. Keep child away from ironing.', 5, false),

(5, 'Mosaic Portrait Tile', '🧩', '#c084fc', 'Arts & Crafts · Fine Motor', 'Arts & Crafts', '30–50 min',
  ARRAY['thick card base', 'small squares of coloured paper or foam', 'glue stick', 'pencil sketch of a face'],
  ARRAY['Sketch a simple face outline on card.', 'Sort paper squares into colour piles.', 'Glue squares across the face area, section by section.', 'Complete background with contrasting tiles.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 4, false),

(5, 'Photography Composition Walk', '📷', '#c084fc', 'Arts & Crafts · Creative', 'Arts & Crafts', '30–50 min',
  ARRAY['tablet or child-safe camera', 'list of composition challenges (close-up, shadow, symmetry, colour)'],
  ARRAY['Introduce three composition ideas: fill the frame, find symmetry, use light.', 'Give the camera to the child.', 'Walk around garden or house finding shots for each challenge.', 'Review photos and discuss favourite and why.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Protect device with a case. Supervise outdoor photography.', 3, false);
