-- Outdoor / Nature activities — ages 0–5, 20 per age group (120 total)
-- Subject: 'Outdoor' — matches existing curated activities
-- Run in Supabase SQL Editor after seed.sql

INSERT INTO activities (age, title, emoji, color, area, subject, duration, materials, steps, prior_stage, prior_desc, safety, ease_of_prep, is_custom) VALUES

-- ── AGE 0 ──────────────────────────────────────────────────────────────────
(0, 'Grass Sensory Blanket', '🌿', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['blanket', 'grassy outdoor area'],
  ARRAY['Lay blanket on short grass in shade.', 'Place baby on back.', 'Hold baby''s hand and brush fingers along grass edge.', 'Let baby feel the different textures of blanket versus grass.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Choose shade; check grass for insects or hazards first.', 2, false),

(0, 'Cloud Watching', '☁️', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['blanket', 'open outdoor area'],
  ARRAY['Lay blanket on grass.', 'Lay baby on back facing up.', 'Point to clouds and describe them slowly.', 'Let baby track moving clouds with eyes.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Keep baby out of direct sun. Hat and sunscreen if warm.', 2, false),

(0, 'Leaf Touch Tray', '🍃', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['variety of large leaves', 'shallow tray'],
  ARRAY['Collect leaves of different sizes and textures.', 'Lay them on a tray at baby''s level.', 'Guide baby''s hand to touch each leaf.', 'Name the texture: smooth, bumpy, soft, crinkly.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Check leaves are non-toxic. Wash hands after.', 2, false),

(0, 'Wind Chime Listening', '🎐', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['wind chimes or hanging ribbon strips', 'tree or hook outside'],
  ARRAY['Hang wind chimes at low height.', 'Hold baby nearby to hear and see.', 'Gently tap chimes to start them.', 'Watch baby''s reaction to sound and movement.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 2, false),

(0, 'Tree Shade Dapple', '🌳', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['blanket', 'leafy tree'],
  ARRAY['Lay blanket under a leafy tree.', 'Place baby on back below the canopy.', 'Let baby watch the light dapple through leaves.', 'Gently shake a low branch to move the pattern.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Check for insects in canopy. Sun protection if bright.', 2, false),

(0, 'Petal Smell Basket', '🌸', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['fragrant petals (lavender, rose)', 'small wicker basket'],
  ARRAY['Collect fragrant petals from garden.', 'Place in basket.', 'Hold near baby''s nose briefly.', 'Observe reaction — move away if baby seems overwhelmed.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Do not place petals in baby''s hands — mouthing risk. Check for pollen allergies.', 2, false),

(0, 'Birdsong Listening Walk', '🐦', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['pram or baby carrier'],
  ARRAY['Go outside during a quiet time of day.', 'Stop near trees or hedgerows.', 'Point toward a bird sound: Can you hear that?', 'Wait quietly and listen together.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 1, false),

(0, 'Rain on the Window', '🌧️', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['rainy day', 'window at baby''s level'],
  ARRAY['Hold baby up to a low window during gentle rain.', 'Point to raindrops sliding down glass.', 'Tap the glass to make drops move.', 'Describe what you see: Look, the rain is running down!'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 1, false),

(0, 'Pinecone Texture Tray', '🌲', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['clean pinecones (2–3)', 'shallow tray'],
  ARRAY['Collect pinecones; brush off dirt.', 'Place in tray in front of baby.', 'Guide baby''s hand to touch the scales.', 'Roll a pinecone slowly; let baby watch.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Check pine cones are clean and have no sharp broken points. Supervise closely.', 2, false),

(0, 'Sun and Shadow Play', '☀️', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['hand', 'sunny outdoor area'],
  ARRAY['Hold baby in your arms in sunlight.', 'Hold up a hand to cast a shadow on baby''s belly.', 'Move hand slowly to shift the shadow.', 'Narrate: The shadow is moving… where did it go?'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Avoid direct sun on baby''s face. Keep sessions brief in heat.', 1, false),

(0, 'Outdoor Sound Jars', '🔔', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['small containers with lids', 'natural fillings: pebbles, dried seeds, sand, acorns'],
  ARRAY['Fill each container with a different natural material.', 'Seal lids tightly.', 'Shake one near baby''s ear.', 'Try each one; watch baby''s reaction to different sounds.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Ensure lids are secure. Check containers for sharp edges.', 3, false),

(0, 'Morning Dew Exploration', '💧', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['early morning garden access', 'blanket'],
  ARRAY['Go outside early while grass is still dewy.', 'Lay blanket and sit baby supported on lap.', 'Touch a dewy leaf and then baby''s hand.', 'Describe the cool dampness.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Keep baby warm. Damp grass — waterproof under blanket.', 1, false),

(0, 'Pebble and Stick Basket', '🪨', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['smooth large pebbles', 'short thick sticks', 'basket'],
  ARRAY['Collect smooth pebbles and thick sticks from garden.', 'Clean and place in basket.', 'Let baby handle each item under close supervision.', 'Describe: Heavy. Cold. Smooth.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Items must be too large to swallow. Constant supervision required.', 2, false),

(0, 'Feather Float Watching', '🪶', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['clean feathers (bought craft feathers)', 'outdoor space'],
  ARRAY['Hold a feather in the air and release.', 'Let baby watch it float down.', 'Catch it before it touches the ground.', 'Repeat; try blowing it to change direction.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Use clean bought feathers. Keep away from baby''s mouth.', 2, false),

(0, 'Tree Bark Rubbing for Baby', '🌲', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['thick tree with rough bark', 'paper', 'chunky crayon'],
  ARRAY['Hold paper against tree bark.', 'Rub crayon across to capture texture.', 'Show finished rubbing to baby.', 'Let baby touch the paper and tree bark alternately.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  NULL, 2, false),

(0, 'Puddle Reflection Looking', '🌊', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['post-rain puddle', 'arms for holding baby'],
  ARRAY['After rain, find a calm puddle.', 'Hold baby and look down together at reflection.', 'Gently toss a pebble in.', 'Watch ripples spread.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Hold baby securely over puddle.', 1, false),

(0, 'Garden Mobile Hanging', '🌀', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['sticks', 'string', 'light natural items: shells, seed pods, leaves'],
  ARRAY['Tie a horizontal stick to a support.', 'Hang natural items on strings of varying lengths.', 'Hang near pram or bouncer outdoors.', 'Let baby watch items move in breeze.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Items must be secured so they cannot fall on baby.', 4, false),

(0, 'Grass Foot Touch', '🦶', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['short soft lawn'],
  ARRAY['Sit on blanket at edge of lawn.', 'Lower baby''s bare feet to touch grass.', 'Let baby feel the grass blades.', 'Watch and narrate baby''s reaction.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Check grass is pesticide-free. Wash feet after.', 1, false),

(0, 'Dandelion Watch', '🌼', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['dandelion clock (seed head)', 'outdoor space'],
  ARRAY['Find a dandelion seed head.', 'Hold in front of baby.', 'Blow seeds off gently.', 'Watch baby track the floating seeds.'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Keep seeds away from baby''s face. Wash hands.', 1, false),

(0, 'Mud Kitchen Watching', '🍳', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '5–15 min',
  ARRAY['bowl of damp soil', 'wooden spoon', 'outdoor table or tray at adult height'],
  ARRAY['Sit with baby on your lap at table.', 'Stir the damp soil with a spoon.', 'Hold baby''s hand to feel cool soil briefly.', 'Name what you are doing: Stirring the mud soup!'],
  'Newborn reflexes', 'Before this stage, sensory experience came from being held, fed and looked at. This activity is an early step into self-directed exploration.',
  'Not for mouthing — wash hands after.', 2, false),

-- ── AGE 1 ──────────────────────────────────────────────────────────────────
(1, 'Puddle Jumping and Splashing', '💧', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '10–20 min',
  ARRAY['rain boots', 'waterproof jacket', 'puddles'],
  ARRAY['Dress in waterproofs after rain.', 'Walk to the nearest puddle.', 'Demonstrate stomping into the puddle.', 'Let child splash as much as they like.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 1, false),

(1, 'Nature Treasure Hunt', '🌿', '#5ed9b1', 'Outdoor · Exploration', 'Outdoor', '10–20 min',
  ARRAY['small basket or bag', 'outdoor area'],
  ARRAY['Give child a basket.', 'Go for a walk and invite them to collect anything interesting.', 'Name each find: A leaf, a pebble, a conker!', 'Spread finds on a blanket and look at them together.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Check all items are non-toxic. No berries or mushrooms.', 1, false),

(1, 'Mud Kitchen Stirring', '🍳', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '10–20 min',
  ARRAY['bowl or old pot', 'wooden spoon', 'soil and water', 'pebbles, leaves, sticks'],
  ARRAY['Set up outdoor mud kitchen at child''s height.', 'Add soil and water to a bowl.', 'Hand child a spoon and let them stir.', 'Add ingredients — leaves, pebbles — and stir more.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Not for eating. Wash hands thoroughly after.', 2, false),

(1, 'Garden Bug Hunt', '🐛', '#5ed9b1', 'Outdoor · Exploration', 'Outdoor', '10–20 min',
  ARRAY['magnifying glass (if available)', 'outdoor area with plants or stones'],
  ARRAY['Go outside and slowly lift a stone or log.', 'Look together at any creatures underneath.', 'Name what you find: worm, woodlouse, beetle.', 'Replace stones carefully.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Wash hands after handling soil and creatures.', 1, false),

(1, 'Chalk Pavement Art', '🖊️', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '10–20 min',
  ARRAY['chunky outdoor chalk', 'paved area'],
  ARRAY['Give child chunky chalk.', 'Demonstrate drawing a big line on pavement.', 'Trace around child''s feet.', 'Let child draw freely.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 1, false),

(1, 'Watering Can Pouring', '🌱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '10–20 min',
  ARRAY['small watering can', 'plant pots or garden bed'],
  ARRAY['Fill a small watering can together.', 'Walk to a plant.', 'Let child tip can to water the plant.', 'Talk about plants needing water to grow.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 2, false),

(1, 'Leaf Sorting and Matching', '🍂', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '10–20 min',
  ARRAY['collected leaves of 3–4 types', 'flat surface or tray'],
  ARRAY['Collect two of each leaf type on a walk.', 'Lay one set out as reference.', 'Give child remaining leaves to sort and match.', 'Celebrate each match.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Wash hands after.', 1, false),

(1, 'Stick and Pebble Sorting', '🪨', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '10–20 min',
  ARRAY['collected sticks and pebbles', 'two containers'],
  ARRAY['Collect a mix of sticks and smooth pebbles.', 'Set out two containers.', 'Let child sort them: pebbles in one, sticks in other.', 'Count each pile together.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Use pebbles and sticks too large to swallow.', 1, false),

(1, 'Snow or Frost Touch', '❄️', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '10–20 min',
  ARRAY['frosty or snowy day', 'warm coat and gloves', 'warm drink for after'],
  ARRAY['Dress warmly and go outside.', 'Touch the frost on a surface together.', 'Scoop snow into hands.', 'Say cold! and watch it melt.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Keep sessions very brief in cold. Warm up indoors after.', 1, false),

(1, 'Pinecone Rolling Race', '🌲', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '10–20 min',
  ARRAY['pinecones (2)', 'slight slope in garden or park'],
  ARRAY['Find a gentle grassy slope.', 'Each person holds a pinecone at the top.', 'Release together.', 'Watch which one rolls further.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Use gentle slopes only.', 1, false),

(1, 'Garden Painting with Water', '💧', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '10–20 min',
  ARRAY['bucket of water', 'fat paintbrush', 'paved area or fence'],
  ARRAY['Fill bucket with water.', 'Give child a big brush.', 'Dip in water and paint fence, paving or wall.', 'Watch the water marks fade and paint again.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 1, false),

(1, 'Bird Feeder Filling', '🐦', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '10–20 min',
  ARRAY['bird seed', 'hanging bird feeder'],
  ARRAY['Fill a small cup with bird seed together.', 'Walk to the feeder.', 'Let child pour seed in.', 'Watch from a window to see if birds come.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Wash hands after handling bird seed.', 2, false),

(1, 'Dandelion Blowing', '🌼', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '10–20 min',
  ARRAY['dandelion seed heads'],
  ARRAY['Find dandelion seed heads together.', 'Hold one up.', 'Show child how to blow.', 'Count seeds remaining.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Keep away from face.', 1, false),

(1, 'Soil and Worm Exploration', '🪱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '10–20 min',
  ARRAY['garden trowel', 'patch of soft soil', 'magnifying glass (optional)'],
  ARRAY['Dig a small area of soil with trowel.', 'Look for worms and other creatures.', 'Observe gently; name what you find.', 'Return soil to cover creatures.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Wash hands thoroughly after.', 2, false),

(1, 'Outdoor Texture Trail', '👣', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '10–20 min',
  ARRAY['socks and shoes on child', 'route with varied surfaces: grass, gravel, bark, smooth path'],
  ARRAY['Walk a short loop over different surfaces.', 'Stop at each surface change.', 'Describe how it feels underfoot.', 'Ask child to stamp or shuffle on each surface.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 1, false),

(1, 'Pebble Tower Building', '🪨', '#5ed9b1', 'Outdoor · Fine Motor', 'Outdoor', '10–20 min',
  ARRAY['smooth flat pebbles', 'flat outdoor surface'],
  ARRAY['Collect flat stones.', 'Stack one on top of another carefully.', 'How high can the tower go before it topples?', 'Rebuild and try a different arrangement.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  NULL, 1, false),

(1, 'Wind Ribbon Wands', '🎀', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '10–20 min',
  ARRAY['sticks', 'coloured ribbon strips (30 cm)', 'tape'],
  ARRAY['Tie ribbon strips to the end of a stick.', 'Give to child outdoors.', 'Run and wave so ribbons stream behind.', 'Twirl and spin to make ribbons move.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Keep ribbon ends from tangling around wrists.', 2, false),

(1, 'Planting Cress Seeds', '🌱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '10–20 min',
  ARRAY['cress seeds', 'damp cotton wool', 'egg cups or small pots'],
  ARRAY['Put damp cotton wool in egg cup.', 'Child sprinkles seeds on top.', 'Place on windowsill.', 'Water gently each day and observe growth over 5–7 days.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Wash hands after handling seeds.', 2, false),

(1, 'Autumn Leaf Pile Jump', '🍂', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '10–20 min',
  ARRAY['fallen leaves', 'rake (optional)', 'open outdoor area'],
  ARRAY['Rake leaves into a big pile together.', 'Show child how to jump in.', 'Take turns running and jumping.', 'Toss leaves in the air together.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'Check pile for hidden sticks before jumping.', 1, false),

(1, 'Outdoor Sorting Tray', '🔵', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '10–20 min',
  ARRAY['muffin tin', 'collection of natural objects: acorns, leaves, pebbles, seeds, sticks'],
  ARRAY['Set muffin tin outside.', 'Collect natural objects together.', 'Place each object in a separate cup.', 'Name and count what fills each section.'],
  'Baby (0–12 months)', 'As a baby, the focus was on watching and being shown. Now the child takes the lead and causes things to happen themselves.',
  'No berries or mushrooms. Wash hands after.', 1, false),

-- ── AGE 2 ──────────────────────────────────────────────────────────────────
(2, 'Mud Pie Making', '🍫', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '15–30 min',
  ARRAY['soil', 'water', 'old bowls, cups, spoons', 'leaves and sticks for decoration'],
  ARRAY['Set up mud kitchen with soil and water.', 'Let child mix mud to their preferred consistency.', 'Form into pies and press into moulds.', 'Decorate with leaves and pebbles.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Not for eating. Wash hands and arms thoroughly after.', 2, false),

(2, 'Simple Nature Mandala', '🌿', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '15–30 min',
  ARRAY['collected natural materials: petals, leaves, pebbles, twigs', 'flat outdoor surface'],
  ARRAY['Place a pebble at the centre.', 'Arrange petals in a ring around it.', 'Add a ring of leaves.', 'Continue outward with sticks and larger stones.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Wash hands after; check for insects in collected materials.', 2, false),

(2, 'Mini Beast Hunt with Log', '🐞', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['old log or large stone', 'magnifying glass', 'tally sheet and crayon'],
  ARRAY['Carefully roll a log or lift a large stone.', 'Count and tally the creatures found.', 'Observe with magnifying glass.', 'Replace log carefully over creatures.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Wash hands after. Teach gentle handling of creatures.', 2, false),

(2, 'Welly Walk in Rain', '🌧️', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '15–30 min',
  ARRAY['wellies', 'waterproof jacket', 'outdoor space with puddles'],
  ARRAY['Put on waterproofs together.', 'Go outside and make a puddle route.', 'Jump in each puddle deliberately.', 'Count how many puddles you found.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 1, false),

(2, 'Sunflower Seed Planting', '🌻', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['sunflower seeds', 'large pot or garden plot', 'compost', 'trowel', 'watering can'],
  ARRAY['Fill pot with compost.', 'Child pokes a finger to make a hole 2 cm deep.', 'Drop in a seed and cover.', 'Water gently; record plant''s growth over weeks.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Wash hands after handling compost.', 3, false),

(2, 'Pebble Painting Outside', '🪨', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '15–30 min',
  ARRAY['smooth pebbles', 'washable paint', 'paintbrushes', 'outdoor table'],
  ARRAY['Wash and dry pebbles.', 'Set up paints at outdoor table.', 'Let child paint a face or pattern on each stone.', 'Leave to dry in sun.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Natural Paintbrush Making', '🖌️', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '15–30 min',
  ARRAY['twigs', 'feathers, grass, leaves', 'elastic bands', 'paint', 'paper'],
  ARRAY['Collect a range of natural materials.', 'Bundle them to the end of a twig with an elastic band.', 'Try painting with each type of brush.', 'Compare the marks each one makes.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Bark Rubbing Collection', '🌲', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['thin paper', 'chunky crayons (paper removed)', 'tape', 'trees with varied bark'],
  ARRAY['Find three trees with different bark textures.', 'Tape paper to bark.', 'Rub side of crayon across paper firmly.', 'Collect one rubbing per tree and compare.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 2, false),

(2, 'Float and Sink Outdoor Test', '⚖️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['large water tray outside', 'natural items: leaf, twig, stone, pine cone, acorn'],
  ARRAY['Fill tray with water.', 'Hold up each item: Will this float or sink?', 'Child places item in water.', 'Sort items into float and sink piles and discuss why.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Supervise near water tray.', 3, false),

(2, 'Shadow Tracing', '☀️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['chalk', 'sunny paved area', 'standing objects or child standing still'],
  ARRAY['Place a toy or stand child in bright sunlight.', 'Trace shadow outline with chalk quickly.', 'Come back 1 hour later; trace shadow again.', 'Compare the two — did it move?'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Sun protection for extended outdoor sessions.', 1, false),

(2, 'Leaf Boat Water Race', '🍃', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['large flat leaves', 'stream, puddle or outdoor water tray', 'stick for pushing'],
  ARRAY['Collect large flat leaves.', 'Set them on still water as boats.', 'Gently push or blow to race them.', 'Try loading a small pebble: does it still float?'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Supervise near moving water.', 1, false),

(2, 'Weather Chart Making', '🌤️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['large paper', 'markers', 'window or outdoor access daily'],
  ARRAY['Make a simple chart with a row for each day.', 'Go outside each morning to observe weather.', 'Draw or stick a symbol: sun, cloud, rain, wind.', 'Review after one week: which was most common?'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 3, false),

(2, 'Insect Hotel Building', '🐝', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['small wooden crate or cardboard box', 'bamboo tubes, pinecones, straw, bark', 'string'],
  ARRAY['Stack bamboo tubes inside box.', 'Fill gaps with pinecones and bark strips.', 'Pack straw into remaining spaces.', 'Tie shut and hang or place in shaded garden corner.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Wash hands after. Check materials for insects first.', 4, false),

(2, 'Seed Collection and Classification', '🌱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['paper bags', 'collected seeds: acorns, berries (known safe), sycamore keys, grass seeds', 'paper and glue'],
  ARRAY['Walk and collect fallen seeds.', 'Sort into groups by type or size.', 'Glue specimens to paper and label together.', 'Talk about how each seed travels (wind, animals).'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Identify all plants before collecting. No unknown berries.', 2, false),

(2, 'Outdoor Obstacle Course', '🏃', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '15–30 min',
  ARRAY['garden equipment: tyres, planks, hoops, cones (improvise with household items)', 'open outdoor space'],
  ARRAY['Set up a simple 5-step course together.', 'Walk through once to show the route.', 'Time child on a run (count together).', 'Change one element and run again.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Check course for sharp edges or trip hazards.', 4, false),

(2, 'Garden Journal Start', '📓', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['notebook', 'pencil', 'coloured pencils', 'outdoor access'],
  ARRAY['Sit outside and look around the garden.', 'Child draws one plant, creature or weather feature.', 'Write date at top (adult scribes).', 'Revisit same spot weekly to see change.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 2, false),

(2, 'Stone Skimming (Throwing Practice)', '🪨', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '15–30 min',
  ARRAY['flat smooth stones', 'large puddle, pond edge or calm water with supervision'],
  ARRAY['Find flat smooth stones together.', 'Practise holding stone at an angle.', 'Throw sidearm toward water.', 'Count splashes or skips.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Maintain safe distance from water edge. Throw away from others.', 1, false),

(2, 'Wind Direction Check', '🌬️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['paper streamers or ribbon strips', 'stick', 'compass (optional)'],
  ARRAY['Tie streamers to stick.', 'Hold up in the air — observe which way they stream.', 'Walk to different spots to check if direction changes.', 'Mark direction with a chalk arrow on path.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  NULL, 2, false),

(2, 'Potted Herb Garden', '🌿', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['herb seedlings (mint, basil, chives)', 'small pots', 'compost', 'trowel', 'watering can'],
  ARRAY['Fill pots with compost.', 'Remove seedling from packet and place in pot.', 'Press compost around roots.', 'Water gently. Smell herbs together.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Wash hands after handling compost.', 3, false),

(2, 'Night Sky Watching', '🌙', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '15–30 min',
  ARRAY['blanket', 'clear dark night', 'torch'],
  ARRAY['Go out after dark on a clear night.', 'Lay blanket and look up.', 'Find the moon; count visible stars.', 'Spot any bright planets or constellations.'],
  '1 year — Wobbler', 'At one, the child explored through grabbing and mouthing. Now they can use simple tools with intention, building wrist and finger control.',
  'Keep session warm and brief for young children.', 1, false),

-- ── AGE 3 ──────────────────────────────────────────────────────────────────
(3, 'Nature Weaving on a Branch', '🌿', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '20–35 min',
  ARRAY['forked branch', 'wool or string for warp', 'natural materials: grasses, leaves, petals, feathers'],
  ARRAY['Tie warp thread back and forth across branch fork.', 'Weave natural materials over and under.', 'Layer different textures and colours.', 'Hang finished piece outside.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 3, false),

(3, 'Outdoor Science: Sink or Float', '⚖️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['large bowl of water outdoors', 'household objects: crayon, spoon, rubber duck, stone, sponge, coin'],
  ARRAY['Before testing, ask child to predict float or sink for each item.', 'Test each one.', 'Group into float and sink piles.', 'Discuss: Why do some float?'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Supervise near water.', 2, false),

(3, 'Bird Spotting Log', '🦅', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['notebook', 'pencil', 'binoculars (toy ones fine)', 'bird identification guide or app'],
  ARRAY['Sit quietly near a bird feeder or garden.', 'Look for birds.', 'When spotted, draw a simple sketch.', 'Try to identify using guide; count different species.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 2, false),

(3, 'Parachute Seed Investigation', '🌱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['dandelion clocks, sycamore keys, thistle seeds', 'magnifying glass', 'paper and pencil'],
  ARRAY['Collect three types of flying seeds.', 'Examine each with a magnifying glass.', 'Drop each from the same height.', 'Observe which travels furthest and discuss why.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 2, false),

(3, 'Mudlark Fossil Making', '🦴', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '20–35 min',
  ARRAY['air-dry clay or salt dough', 'leaves, shells, sticks, feathers for imprinting', 'rolling pin'],
  ARRAY['Roll clay flat outdoors.', 'Press natural objects firmly into surface.', 'Remove objects carefully.', 'Let clay dry in sun to make fossils.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 3, false),

(3, 'Outdoor Kitchen Soup', '🍵', '#5ed9b1', 'Outdoor · Sensory', 'Outdoor', '20–35 min',
  ARRAY['outdoor mud kitchen or bowls', 'water', 'leaves, petals, grass, soil', 'wooden spoons'],
  ARRAY['Fill a pot with water.', 'Collect outdoor ingredients together.', 'Child adds each ingredient with commentary.', 'Stir vigorously and serve pretend portions.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Not for eating. Wash hands after.', 2, false),

(3, 'Grow Your Own Salad', '🥗', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['lettuce or radish seeds', 'planter trough', 'compost', 'trowel', 'watering can'],
  ARRAY['Fill trough with compost.', 'Scatter seeds across surface.', 'Cover with thin layer of compost.', 'Water daily; harvest and eat leaves in 3–4 weeks.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Wash produce before eating. Wash hands after gardening.', 3, false),

(3, 'Outdoor Sound Map', '🗺️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['paper', 'coloured pencils', 'outdoor area'],
  ARRAY['Sit in garden or park and listen with eyes closed for 30 seconds.', 'List all sounds heard.', 'Draw a simple map and mark where each sound came from.', 'Walk toward each source to confirm.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 2, false),

(3, 'Conker Catapult Physics', '🌰', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['conkers or small stones', 'flat plank and a fulcrum (a log)', 'chalk for landing marks'],
  ARRAY['Balance plank on log to create lever.', 'Place conker on one end.', 'Stamp the other end to launch conker.', 'Mark where it lands; try varying distance from fulcrum.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Clear the landing zone of people before launching.', 4, false),

(3, 'Outdoor Art Gallery', '🖼️', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '20–35 min',
  ARRAY['child''s existing artwork', 'string or washing line', 'pegs', 'outdoor space'],
  ARRAY['Select a few pieces of artwork together.', 'Hang on a washing line outside.', 'Invite family to view the gallery.', 'Child explains each piece to visitors.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 3, false),

(3, 'Rainbow in a Jar Outside', '🌈', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['clear jar', 'water', 'torch or sunlight'],
  ARRAY['Fill jar completely with water.', 'Hold in direct sunlight or shine torch through it.', 'Project light onto white paper to see rainbow.', 'Move jar to change position of rainbow.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 2, false),

(3, 'Den Building', '🏕️', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '20–35 min',
  ARRAY['sticks and branches', 'tarpaulin or old sheet', 'string', 'outdoor space'],
  ARRAY['Choose a site: between two trees or against a wall.', 'Lean large sticks against a support.', 'Drape sheet over frame.', 'Secure with string; fill with blankets for cosy inside.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Ensure structure is stable before child enters.', 4, false),

(3, 'Soil pH Test (Simple)', '🔬', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['garden soil', 'two jars', 'vinegar', 'bicarbonate of soda', 'water'],
  ARRAY['Collect soil from garden.', 'Put soil in two jars, add water.', 'In one jar add vinegar: fizzing means alkaline.', 'In other add bicarb: fizzing means acidic. Compare!'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 4, false),

(3, 'Rock and Pebble Painting Gallery', '🪨', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '20–35 min',
  ARRAY['smooth pebbles', 'acrylic paint', 'small brushes', 'PVA sealer'],
  ARRAY['Wash and dry pebbles.', 'Paint animals, faces or patterns.', 'Let dry and seal with PVA.', 'Place painted rocks around garden as outdoor gallery.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 3, false),

(3, 'Adopt a Tree', '🌳', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['local tree', 'notebook', 'pencil', 'measuring tape'],
  ARRAY['Choose a local tree to observe across seasons.', 'Sketch the tree and describe it.', 'Measure trunk circumference.', 'Return each month and record changes.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 2, false),

(3, 'Homemade Pinwheel', '🌬️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['square paper', 'pin', 'pencil with eraser', 'scissors (adult use)'],
  ARRAY['Decorate a square of paper.', 'Adult makes diagonal cuts from corners to near centre.', 'Fold every other point to centre.', 'Pin through centre into pencil eraser.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Adult handles pin and scissors.', 4, false),

(3, 'Map of the Garden', '🗺️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['paper', 'pencil', 'coloured pencils', 'outdoor space'],
  ARRAY['Walk around the garden and discuss what''s there.', 'Back at table, draw outline of garden shape.', 'Add key features: trees, paths, shed, flower beds.', 'Add a compass rose and legend.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  NULL, 2, false),

(3, 'Bird Feeder Making', '🐦', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['pine cone', 'peanut butter or suet', 'bird seed', 'string'],
  ARRAY['Tie string to top of pine cone.', 'Roll pine cone in peanut butter.', 'Roll in bird seed.', 'Hang from tree and watch for birds.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Wash hands after. Check for nut allergies in household.', 3, false),

(3, 'Soil Layers Model', '🌍', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '20–35 min',
  ARRAY['clear jar', 'gravel', 'sand', 'soil', 'leaves or grass', 'water'],
  ARRAY['Place a layer of gravel in jar.', 'Add sand on top.', 'Add soil layer.', 'Top with leaves. Pour water in slowly and observe filtration.'],
  '2 years — Tiny explorer', 'Two-year-olds explored textures freely. Now they can follow a simple sequence and start to talk about what they see.',
  'Wash hands after handling soil.', 3, false),

-- ── AGE 4 ──────────────────────────────────────────────────────────────────
(4, 'Nature Documentary Making', '🎥', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '25–40 min',
  ARRAY['tablet or phone for filming (adult phone)', 'outdoor area', 'simple script prompt card'],
  ARRAY['Plan a short documentary: choose a creature or plant to report on.', 'Find the subject outdoors.', 'Child narrates what they observe while adult films.', 'Watch back and discuss.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Supervise device use outdoors.', 2, false),

(4, 'Ecosystem in a Bottle', '🌱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['large clear plastic bottle', 'gravel', 'soil', 'small plants or seeds', 'water'],
  ARRAY['Adult cuts bottle in half.', 'Layer gravel, then soil in bottom half.', 'Plant small plants or seeds.', 'Water lightly; place top half as lid. Seal with tape.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Adult handles cutting plastic. Observe condensation cycle.', 5, false),

(4, 'Compass Navigation Walk', '🧭', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['simple compass', 'map of local area or park', 'notebook'],
  ARRAY['Show child how compass needle points north.', 'Orient map to match compass direction.', 'Plan a route: Go north for 50 steps, then east.', 'Follow the route and record landmarks.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Keep route in safe familiar area. Adult accompanies.', 3, false),

(4, 'Weather Station Setup', '🌡️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['thermometer (outdoor)', 'rain gauge (plastic cup with ruler)', 'pinwheel wind speed indicator', 'notebook'],
  ARRAY['Set up thermometer in shade.', 'Place rain gauge in open area.', 'Add pinwheel as wind indicator.', 'Record readings morning and afternoon for one week.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 5, false),

(4, 'Pond Dipping', '🐸', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['pond dipping net', 'white tray', 'magnifying glass', 'identification guide', 'wellies'],
  ARRAY['Approach pond edge slowly.', 'Sweep net through water and empty into white tray.', 'Identify creatures using guide.', 'Gently return all creatures to pond.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Strict supervision near water edge. Wash hands after.', 3, false),

(4, 'Garden Biodiversity Survey', '🔬', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['1m × 1m quadrat (string and sticks)', 'notebook', 'magnifying glass', 'tally sheet'],
  ARRAY['Peg out a 1m² quadrat on lawn.', 'Count and record every species of plant inside it.', 'Look for insects and creatures.', 'Compare with a second quadrat in a different spot.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Wash hands after. Check for bees before kneeling.', 3, false),

(4, 'Rainwater Collection Experiment', '🌧️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['several containers of different widths', 'ruler', 'rainy day or watering can'],
  ARRAY['Set out containers of different widths outside.', 'Let rain collect (or simulate with watering can).', 'After 10 minutes, measure water depth in each.', 'Compare: same depth or different? Why?'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 3, false),

(4, 'Build a Bug Hotel', '🐝', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['wooden pallet or crate', 'bamboo tubes', 'straw', 'pinecones', 'bark', 'dry leaves', 'string'],
  ARRAY['Choose a shaded outdoor spot.', 'Fill layers of crate with different materials.', 'Pack each layer tightly.', 'Mount or place flat; check for visitors over coming weeks.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Wash hands after. Check for resident insects before handling.', 5, false),

(4, 'Nature Photography Project', '📷', '#5ed9b1', 'Outdoor · Creative', 'Outdoor', '25–40 min',
  ARRAY['tablet or camera', 'notebook', 'pencil', 'outdoor area'],
  ARRAY['Choose a theme: colours, textures, tiny things.', 'Walk and photograph examples.', 'Review photos.', 'Create a simple printed or drawn gallery with labels.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 3, false),

(4, 'Outdoor Shadow Sundial', '☀️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['vertical stick in soil', 'chalk or small stones', 'open sunny area'],
  ARRAY['Push stick upright into soil.', 'Mark shadow tip with a stone or chalk at 9 am.', 'Return each hour and mark again.', 'After 4 marks, discuss how sun moves across sky.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Sunscreen for extended outdoor time.', 2, false),

(4, 'Soil Permeability Test', '💧', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['3 plastic bottles with holes poked in base', 'gravel, sand, clay soil', 'measuring jug', 'water'],
  ARRAY['Fill each bottle with a different material.', 'Pour same amount of water into each.', 'Time how long water takes to drain through.', 'Record and rank from fastest to slowest.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 5, false),

(4, 'Homemade Rain Gauge', '🌧️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['clear plastic bottle', 'ruler', 'permanent marker', 'outdoor spot'],
  ARRAY['Cut bottle and mark measurements on inside.', 'Place in open spot away from drip zones.', 'Read measurement after each rain.', 'Chart rainfall over two weeks.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Adult cuts bottle. Ensure stable placement.', 4, false),

(4, 'Minibeast Pitfall Trap', '🐛', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['yogurt pot', 'trowel', 'damp soil area', 'stone for lid', 'magnifying glass'],
  ARRAY['Dig hole to fit yogurt pot.', 'Place pot flush with soil surface.', 'Cover lightly with a stone (leave gap for insects).', 'Check next morning; identify captures, record, then release.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Release all creatures within 24 hours. Wash hands after.', 3, false),

(4, 'Leaf Identification Key', '🍂', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['collected leaves (at least 5 species)', 'plant identification book or app', 'paper', 'pencil'],
  ARRAY['Collect a range of fallen leaves.', 'Lay flat and examine shape, edge and vein pattern.', 'Use identification key to name each.', 'Make a simple hand-drawn leaf key to display.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Wash hands after handling soil and leaves.', 2, false),

(4, 'Outdoor Maths Trail', '🔢', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '25–40 min',
  ARRAY['pencil', 'trail sheet with tasks: Find 5 pebbles. Measure a stick. Count petals.', 'measuring tape'],
  ARRAY['Print or write a maths trail card.', 'Walk route and complete each task.', 'Record answers on sheet.', 'Review at end: were estimates accurate?'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 3, false),

(4, 'Tidal Zone Model (Water Tray)', '🌊', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['large water tray', 'sand', 'pebbles', 'shells', 'small figures', 'jug of water'],
  ARRAY['Create a tiered beach: deep water zone, shore, dry sand.', 'Add shells and figures to different zones.', 'Pour water slowly to simulate tide coming in.', 'Remove water to show tide going out; discuss which creatures live where.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Supervise near water tray.', 5, false),

(4, 'Garden Experiment Journal', '📓', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['notebook', 'pencil', 'seeds', 'pots and compost'],
  ARRAY['Design a simple experiment: same seed, different conditions (light vs dark).', 'Write prediction before planting.', 'Observe and draw results weekly.', 'Write conclusion: My prediction was right/wrong because…'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 4, false),

(4, 'Stone Balance Sculpture', '🪨', '#5ed9b1', 'Outdoor · Fine Motor', 'Outdoor', '25–40 min',
  ARRAY['stones and pebbles of varied sizes', 'flat outdoor surface'],
  ARRAY['Begin with largest stone as base.', 'Place progressively smaller stones on top.', 'Find balance point before releasing each stone.', 'Photograph finished sculpture.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  NULL, 1, false),

(4, 'Compost Bin Start', '♻️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '25–40 min',
  ARRAY['compost bin or large pot with drainage holes', 'vegetable peels, garden clippings', 'soil', 'trowel'],
  ARRAY['Layer garden clippings in bin.', 'Add a layer of vegetable peels.', 'Cover with a thin layer of soil.', 'Water lightly; revisit weekly to observe decomposition.'],
  '3 years — Curious kid', 'At three, play was about doing. Now the child can hold a goal in mind and plan a couple of steps ahead.',
  'Wash hands after. No meat or dairy in compost.', 4, false),

-- ── AGE 5 ──────────────────────────────────────────────────────────────────
(5, 'Design a Wildlife Garden Zone', '🦋', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['paper', 'coloured pencils', 'seed packets', 'plant labels'],
  ARRAY['Research which plants attract which creatures.', 'Design a corner of the garden on paper.', 'Choose 3 plants to grow for wildlife.', 'Plant, label and monitor for visiting creatures.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Wash hands after planting.', 5, false),

(5, 'Water Cycle Investigation', '💧', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['zip-lock bag', 'water', 'blue food colouring', 'sunny window or outdoor surface'],
  ARRAY['Add a small amount of coloured water to zip bag.', 'Seal and tape to a sunny surface.', 'Observe over 30 minutes: condensation then drips.', 'Discuss evaporation, condensation, precipitation.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 2, false),

(5, 'Orienteering Course', '🧭', '#5ed9b1', 'Outdoor · Active', 'Outdoor', '30–50 min',
  ARRAY['compass', 'hand-drawn map of garden or park', 'numbered hidden clues at each waypoint'],
  ARRAY['Hide clue cards at 6 waypoints.', 'Give child the map and compass.', 'Child navigates to each waypoint in order.', 'Collect clue cards to complete a message.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Set course within safe, supervised boundary.', 5, false),

(5, 'Food Chain Web in the Garden', '🌿', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['string', 'labels with plant and creature names', 'outdoor space'],
  ARRAY['Write creature and plant names on labels.', 'Each person holds a label.', 'String connects who eats whom.', 'Remove one link — what happens to the web?'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 4, false),

(5, 'Solar System Scale Model', '🪐', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['balls of varied sizes', 'chalk or stakes', 'long measuring tape', 'planet size/distance data sheet'],
  ARRAY['Scale planet sizes to fit garden.', 'Mark sun position.', 'Pace scaled distances for each planet.', 'Place scaled ball at each position.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'May need a longer outdoor space (park).', 5, false),

(5, 'Erosion and River Delta Model', '🏔️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['sand tray on a slope', 'watering can', 'notebook'],
  ARRAY['Build a raised sand mound at one end of tray.', 'Slowly pour water from watering can at top.', 'Observe channels forming as water flows down.', 'Sketch the delta pattern formed.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 4, false),

(5, 'Plant Transpiration Test', '🌿', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['leafy plant stem in a jar of water', 'plastic bag', 'elastic band', 'sunny spot'],
  ARRAY['Place plastic bag over a leafy branch.', 'Seal with elastic band.', 'Leave in sun for 2 hours.', 'Observe water droplets inside bag — plant breathed out water!'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 3, false),

(5, 'Edible Wild Plant Identification', '🌿', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['identification guide for edible plants', 'gloves', 'basket', 'an expert adult guide'],
  ARRAY['Learn to identify 3 safe wild plants (dandelion, clover, plantain).', 'Find each plant on a walk.', 'Confirm identification carefully.', 'Taste a leaf of each (wash first).'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Only forage known safe plants with adult expert guidance. Never guess.', 4, false),

(5, 'Tide Pool Journaling', '🌊', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['waterproof notebook or clipboard with paper', 'pencil', 'magnifying glass', 'identification guide', 'wellies'],
  ARRAY['Visit a rocky shore at low tide.', 'Find 3 different rock pools.', 'Sketch creatures found in each.', 'Identify and label using guide.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Supervise strictly near rock pools and sea. Wear wellies.', 2, false),

(5, 'Seed Dispersal Experiment', '🌱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['four types of seed: sycamore, dandelion, coconut (model), apple pip', 'fan or outdoor breeze', 'notebook'],
  ARRAY['Examine each seed structure.', 'Predict which will travel furthest in wind.', 'Drop each from the same height outdoors on a breezy day.', 'Measure travel distance and record.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 3, false),

(5, 'Build and Test a Shelter', '🏕️', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['sticks, leaves, bark', 'small figure or toy to shelter', 'watering can for rain test'],
  ARRAY['Plan shelter design: what shape will shed water best?', 'Collect and build using natural materials only.', 'Test waterproofing with gentle water pour.', 'Improve design based on results.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 3, false),

(5, 'Citizen Science Bug Count', '🐝', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['tally sheet for common species', 'pencil', 'magnifying glass', '1m² quadrat string', 'identification guide'],
  ARRAY['Peg out quadrat on a flower bed or lawn.', 'Sit still and watch for 5 minutes.', 'Tally each insect species spotted.', 'Submit findings to a citizen science app or record in journal.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Teach gentle observation — no capturing or disturbing.', 2, false),

(5, 'Rock Cycle in a Box', '🪨', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['crayons (wax)', 'grater', 'foil', 'hot water flask (adult use)', 'heavy book'],
  ARRAY['Grate crayon shavings — sediment.', 'Press together with book — sedimentary rock.', 'Wrap in foil and hold near warm flask — metamorphic rock.', 'Discuss: what would igneous require? (melting — too hot for us!).'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Adult handles hot flask. Never melt crayon directly.', 5, false),

(5, 'Outdoor Geometry Hunt', '🔢', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['shape checklist', 'pencil', 'camera or sketch pad'],
  ARRAY['Make checklist of shapes: circle, hexagon, spiral, triangle, rectangle.', 'Walk and find real-world examples of each.', 'Photograph or sketch each find with label.', 'Discuss where geometry appears in nature (honeycomb, spiral shell).'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 2, false),

(5, 'Grow and Measure Runner Beans', '📏', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['runner bean seeds', 'large pot', 'canes', 'string', 'compost', 'ruler', 'growth chart'],
  ARRAY['Plant 2 seeds per pot.', 'Set up canes for climbing.', 'Measure height weekly and plot on chart.', 'Count leaves and flowers as season progresses.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Wash hands after gardening.', 4, false),

(5, 'Night Creature Investigation', '🦔', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['torch with red filter (less disruptive to wildlife)', 'notebook', 'pencil', 'hedgehog food (optional)'],
  ARRAY['Go out at dusk in the garden.', 'Move quietly and observe.', 'Record any creatures seen or heard (owl, bat, hedgehog, moth).', 'Leave food for hedgehog if found.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Adult accompanies at all times. Brief, warm session.', 2, false),

(5, 'Make a Wormery', '🪱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['large clear container', 'alternating layers of soil and sand', 'leaf litter', 'worms from garden', 'dark paper for cover'],
  ARRAY['Layer sand and soil alternately in container.', 'Add leaf litter on top.', 'Place worms on surface and watch them burrow.', 'Cover with dark paper; check in 24 hours to see tunnel activity.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Handle worms gently. Return to garden after 2–3 days.', 4, false),

(5, 'Climate Change Tree Planting', '🌱', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['native tree sapling (oak, hazel, rowan)', 'spade', 'compost', 'stake and tie', 'watering can'],
  ARRAY['Dig hole twice width of root ball.', 'Place sapling; backfill with soil and compost.', 'Firm down; water well.', 'Add stake for support; discuss why trees matter for climate.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  'Adult handles spade. Check planting site for underground pipes.', 5, false),

(5, 'Phenology Journal', '📅', '#5ed9b1', 'Outdoor · Science', 'Outdoor', '30–50 min',
  ARRAY['blank journal', 'pencil', 'coloured pencils', 'regular outdoor access'],
  ARRAY['Introduce the word phenology: tracking seasonal nature events.', 'Record first sightings: first bud, first swallow, first frost.', 'Draw and date each event.', 'Compare to records from previous year if available.'],
  '4 years — Pre-schooler', 'Pre-schoolers loved imaginative play. By five they can layer in rules, sequences and longer narratives — early formal learning skills.',
  NULL, 2, false);
